App\Entity\Translation:
    attributes:
        normalization_context:
            groups: ["read", "write"]
        denormalization_context:
            groups: ["write"]

App\Entity\Lesson:
    attributes:
        normalization_context:
            groups: ["read", "write"]
        denormalization_context:
            groups: ["write"]
