# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]    
    app.lesson_manager:
        class: AppBundle\Manager\LessonManager
        arguments: ['@doctrine.orm.entity_manager', '@session']

    app.exercise_manager:
        class: AppBundle\Manager\ExerciseManager
        arguments: ['@doctrine.orm.entity_manager']
