services:
    app.lesson_manager:
        class: AppBundle\Manager\LessonManager
        arguments: ['@doctrine.orm.entity_manager', '@session']

    app.book_lesson_manager:
        class: AppBundle\Manager\BookLessonManager
        arguments: ['@doctrine.orm.entity_manager']

    app.study_manager:
        class: AppBundle\Manager\StudyManager
        arguments: ['@doctrine.orm.entity_manager', '@session', '@app.lesson_manager', '@app.exercise_manager']

    app.learning_manager:
        class: AppBundle\Manager\LearningManager
        arguments: ['@doctrine.orm.entity_manager']

    app.corrector.regex:
        class: AppBundle\Model\RegexCorrector
        arguments: ['@logger']

    app.exercise_manager:
        class: AppBundle\Manager\ExerciseManager
        arguments: ['@doctrine.orm.entity_manager', '@app.corrector.regex']

    app.complaint_manager:
        class: AppBundle\Manager\ComplaintManager
        arguments: ['@doctrine.orm.entity_manager']
