#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

authentication_token:
    path: /api/authentication_token
    methods: ['POST']

